import { test, expect } from "@playwright/test";
import { mkdir, readFile } from "node:fs/promises";

test("real decision percentages, checkbox selection, evidence and actual unavailable action", async ({page,request}) => {
  const catalog = await (await request.get("/api/datasets/catalog")).json();
  const table = await (await request.get("/api/datasets/decisions",{params:{version:catalog.version,selection:"cpu-placement,idle-sessions"}})).json();
  expect(table.synthetic).toBe(false);
  expect(table.total_gpu_hours).toBeCloseTo(catalog.summary.gpu_hours,6);
  expect(table.rows).toHaveLength(8);
  expect(table.rows.every((r: {allocated_share_pct:number}) => r.allocated_share_pct >= 0 && r.allocated_share_pct <= 100)).toBe(true);
  expect(table.selection.overlapping_gpu_hours).toBeGreaterThan(0);
  expect(table.selection.gpu_hours).toBeLessThan(table.rows.slice(0,2).reduce((n:number,r:{allocated_gpu_hours:number}) => n+r.allocated_gpu_hours,0));
  await page.goto("/#optimization");
  await expect(page.getByRole("heading",{name:"Optimization opportunities",exact:true})).toBeVisible();
  await expect(page.getByRole("table")).toBeVisible();
  await expect(page.getByRole("row")).toHaveCount(9);
  await expect(page.getByRole("heading",{name:"What does a 20% cut mean?",exact:true})).toBeHidden();
  const overview=page.getByRole("region",{name:"CFO decision overview"});
  await expect(overview).toBeVisible();
  await expect(overview.getByText("Estimate pending",{exact:true})).toBeVisible();
  const legend=overview.getByRole("list");
  const cancelled=catalog.summary.outcomes.filter((o:{outcome:string}) => o.outcome === "CANCELLED").reduce((sum:number,o:{gpu_hours:number}) => sum+o.gpu_hours,0)/catalog.summary.gpu_hours*100;
  await expect(legend.getByRole("listitem").filter({hasText:"Cancelled"})).toContainText(`${cancelled.toFixed(1)}%`);
  await overview.getByText("Scope and calculation",{exact:true}).click();
  await expect(page.getByText(/Someone cancelled this work/)).toBeVisible();
  await overview.getByText("Scope and calculation",{exact:true}).click();
  await page.getByText("About the optional 20% spending goal",{exact:true}).click();
  await expect(page.getByRole("heading",{name:"What does a 20% cut mean?",exact:true})).toBeVisible();
  await page.getByText("About the optional 20% spending goal",{exact:true}).click();
  await expect(page.getByRole("table")).toBeVisible();
  const cpu=page.getByRole("checkbox",{name:"Select CPU placement pilot",exact:true});
  await expect(cpu).toBeEnabled();
  await cpu.focus();
  await page.keyboard.press("Space");
  await expect(cpu).toBeChecked();
  await page.getByRole("checkbox",{name:"Select Idle interactive sessions",exact:true}).check();
  await expect(page.getByRole("button",{name:"Optimize selected"})).toBeEnabled();
  await expect(page.getByText("What could go wrong?",{exact:true})).toHaveCount(0);
  await mkdir(".local-data/evidence",{recursive:true});
  await page.screenshot({path:".local-data/evidence/optimization-desktop.png",fullPage:true});
  let sent=0;
  page.on("request",r => {if(r.url().endsWith("/api/optimizations") && r.method()==="POST") sent++;});
  const trigger=page.getByRole("button",{name:"Optimize selected"});
  await trigger.click();
  const popup=page.getByRole("dialog",{name:"Optimize 2 selected tasks?"});
  await expect(popup.getByText(`${table.selection.share_pct.toFixed(1)}%`,{exact:true})).toBeVisible();
  await expect(popup.getByText("What could go wrong?",{exact:true})).toHaveCount(2);
  const reviewDownload=page.waitForEvent("download");
  await popup.getByRole("button",{name:"Download decision review"}).click();
  const file=await reviewDownload;
  expect(file.suggestedFilename()).toBe("decision-review.example.json");
  const review=JSON.parse(await readFile((await file.path())!,"utf8"));
  expect(review.dataset_version).toBe(catalog.version);
  expect(review.selection).toEqual(table.selection);
  expect(review.actions.map((a:{id:string}) => a.id)).toEqual(table.selection.fix_ids);
  expect(review.combined_net_savings).toBeNull();
  expect(review.verified_cash_savings).toBeNull();
  expect(review.status).toBe("not-approved-not-executed");
  await popup.getByRole("button",{name:"Return",exact:true}).focus();
  await expect(popup.getByRole("button",{name:"Return",exact:true})).toBeFocused();
  for(let i=0;i<7;i++) {await page.keyboard.press("Tab");expect(await popup.evaluate(el => el.contains(document.activeElement))).toBe(true);}
  await page.keyboard.press("Escape");
  await expect(popup).toHaveCount(0);await expect(trigger).toBeFocused();expect(sent).toBe(0);
  await trigger.click();await popup.getByRole("button",{name:"Return",exact:true}).click();
  await expect(trigger).toBeFocused();expect(sent).toBe(0);
  await trigger.click();
  await popup.screenshot({path:".local-data/evidence/optimize-popup-desktop.png"});
  const outbound=page.waitForRequest(r => r.url().endsWith("/api/optimizations") && r.method() === "POST");
  await popup.getByRole("button",{name:"Proceed",exact:true}).click();
  expect((await outbound).postDataJSON()).toMatchObject({mode:"model_only",cancelled_policy:"exclude",expected_dataset_version:catalog.version,fix_ids:["cpu-placement","idle-sessions"]});
  await expect(page.getByRole("alert")).toContainText("Optimization was not confirmed");
  await expect(popup.getByRole("button",{name:"Download decision review"})).toBeEnabled();
  await expect(cpu).toBeChecked();
  await page.getByRole("dialog").getByRole("button",{name:"Return",exact:true}).click();
  await page.getByRole("row").filter({has:cpu}).getByRole("link").click();
  await expect(page.getByLabel("Search findings")).toHaveValue("rules::gpu-not-needed");
  await expect(page.getByRole("cell",{name:"rules::gpu-not-needed",exact:true}).first()).toBeVisible();
  await expect(page.getByLabel("Status",{exact:true}).getByRole("option",{name:"Historical",exact:true})).toBeAttached();
});

test("mobile decision cards keep fixes visible and accept a stubbed matching backend receipt", async ({page}) => {
  await page.route("**/api/optimizations",async route => {
    const input=route.request().postDataJSON();
    await route.fulfill({json:{contract_version:input.contract_version,client_request_id:input.client_request_id,dataset_version:input.expected_dataset_version,mode:"model_only",fix_ids:input.fix_ids,status:"accepted",optimization_id:"browser-stub-only",synthetic:false}});
  });
  await page.setViewportSize({width:390,height:844});
  await page.goto("/#optimization");
  const summaryReview=page.getByRole("button",{name:"Review pilot risks",exact:true});
  await summaryReview.click();
  await expect(page.getByRole("dialog").getByText("2.0%",{exact:true})).toBeVisible();
  await page.getByRole("dialog").getByRole("button",{name:"Return",exact:true}).click();
  await expect(summaryReview).toBeFocused();
  await expect(page.getByRole("checkbox",{name:"Select CPU placement pilot",exact:true})).toBeChecked();
  await expect(page.getByRole("button",{name:"Optimize selected"})).toBeEnabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByText("What could go wrong?",{exact:true})).toHaveCount(0);
  await page.screenshot({path:".local-data/evidence/optimization-mobile.png",fullPage:true});
  await page.getByRole("button",{name:"Optimize selected"}).click();
  const popup=page.getByRole("dialog");
  await expect(popup.getByText("What could go wrong?",{exact:true})).toBeVisible();
  expect(await popup.evaluate(el => el.scrollWidth<=el.clientWidth)).toBe(true);
  await popup.screenshot({path:".local-data/evidence/optimize-popup-mobile.png"});
  await popup.getByRole("button",{name:"Proceed",exact:true}).click();
  await expect(page.getByText("Backend accepted your modeling request",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Request accepted",exact:true})).toBeDisabled();
});
