import {test,expect} from "@playwright/test";
import {readFile,mkdir} from "node:fs/promises";
for(const mobile of [false,true]) test(`CPU pilot comparison, downside and immutable export (${mobile ? "mobile" : "desktop"})`,async ({page,request}) => {
  if(mobile) await page.setViewportSize({width:390,height:844});
  await page.goto("/#optimization");
  await page.getByRole("button",{name:"Compare CPU pilot",exact:true}).click();
  await expect(page.getByRole("region",{name:"Should we run the CPU pilot?"})).toBeFocused();
  await expect(page.getByLabel("CPU price ($/core-hour)",{exact:true})).toBeHidden();
  await page.getByText("Engineering assumptions and pilot limits",{exact:true}).click();
  await page.getByRole("button",{name:"Compare pilot scenarios",exact:true}).click();
  await expect(page.getByRole("alert")).toContainText("Complete every numeric assumption");
  const fields:{[key:string]:string}={"CPU price ($/core-hour)":"0.05","CPU core-hours — low":"100","CPU core-hours — base":"200","CPU core-hours — high":"400","Implementation cost ($)":"50","Extra retry / rollback reserve ($)":"25","Worst modeled slowdown (%)":"50","Assumption source / evidence":"Illustrative browser scenario, not measured CPU performance."};
  for(const [label,value] of Object.entries(fields)) await page.getByLabel(label,{exact:true}).fill(value);
  await page.getByRole("button",{name:"Compare pilot scenarios",exact:true}).click();
  const result=page.getByRole("region",{name:"Calculated pilot result"});
  await expect(result.getByRole("heading",{name:"Revise this pilot before approval"})).toBeVisible();
  await expect(result.getByText("Unpriced downside",{exact:true})).toBeVisible();
  await expect(result.getByText("Modeled slowdown exceeds your limit.",{exact:false})).toBeVisible();
  await page.getByLabel("Implementation cost ($)",{exact:true}).fill("999");
  await expect(result.getByRole("status")).toContainText("Unsaved assumptions");
  const downloaded=page.waitForEvent("download");
  await result.getByRole("button",{name:"Download calculated pilot plan"}).click();
  const file=await downloaded;
  expect(file.suggestedFilename()).toBe("cpu-pilot-plan.example.json");
  const plan=JSON.parse(await readFile((await file.path())!,"utf8"));
  expect(plan.inputs.implementation).toBe("50");
  const catalog=await (await request.get("/api/datasets/catalog")).json();
  const decisions=await (await request.get("/api/datasets/decisions",{params:{version:catalog.version,selection:"cpu-placement"}})).json();
  const hours=decisions.rows.find((r:{id:string}) => r.id === "cpu-placement").allocated_gpu_hours*.05;
  expect(plan.source.version).toBe(catalog.version);
  expect(plan.result.scenarios[0].net).toBe(-95);
  expect(plan.result.scenarios[1].net).toBeCloseTo(hours*.5*2.5-85,6);
  expect(plan.result.target).toBeCloseTo(catalog.summary.gpu_hours*2.5*.2,6);
  expect(plan.result.extraSpend).toBe(95);
  expect(plan.result.slowdownBreached).toBe(true);
  expect(plan.status).toBe("not-approved-not-executed");
  expect(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await mkdir(".local-data/evidence",{recursive:true});
  await page.locator("#cpu-pilot-planner form").screenshot({path:`.local-data/evidence/pilot-inputs-${mobile ? "mobile" : "desktop"}.png`});
  await result.screenshot({path:`.local-data/evidence/pilot-${mobile ? "mobile" : "desktop"}.png`});
  await page.getByLabel("Implementation cost ($)",{exact:true}).fill("50");
  await page.getByLabel("Maximum acceptable slowdown (%)",{exact:true}).fill("60");
  await page.getByRole("button",{name:"Compare pilot scenarios",exact:true}).click();
  await expect(result.getByRole("heading",{name:"Candidate for an owner-reviewed pilot"})).toBeVisible();
  await result.getByText("Calculation and assumption provenance",{exact:true}).click();
  await result.getByRole("link",{name:"Inspect CPU pilot source evidence"}).click();
  await expect(page.getByLabel("Search findings")).toHaveValue("rules::gpu-not-needed");
});
