/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service liveness plus explicit data/agent readiness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source sample spending overview; not recoverable savings */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source judgments plus team audit availability */
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create immutable scenario audit; no infrastructure action */
        post: operations["createAudit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read immutable audit snapshot */
        get: operations["getAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page through audit-scoped evidence references */
        get: operations["listAuditEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a reference belonging to this audit */
        get: operations["getAuditEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bounded MCP-backed explanation; cannot alter audit */
        post: operations["explainAudit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Official-schema-compatible export of this exact audit */
        get: operations["exportClaims"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Required template-based chatbot using real official MCP tools; independent of optional reviewer */
        post: operations["answerBaseChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
                retryable: boolean;
                request_id: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Provenance: {
            data_fingerprint: string;
            sample_label: string;
            window_label: string;
            synthetic: boolean;
            source_version: string;
            caveats: string[];
        };
        Interval: {
            low: number;
            point: number;
            high: number;
        };
        RecoveryFractions: {
            low: number;
            point: number;
            high: number;
        };
        MoneyRange: {
            /** @enum {string} */
            currency: "USD";
            /** @enum {string} */
            unit: "reference_usd";
            values: components["schemas"]["Interval"];
            /** @constant */
            cash_savings_verified: false;
        };
        Scenario: {
            recovery_fraction: components["schemas"]["RecoveryFractions"];
            usd_per_gpu_hour: number;
            /** @enum {string} */
            cancelled_policy: "exclude";
            /** @enum {string} */
            interval_kind: "scenario";
            assumption_note: string;
        };
        AuditRequest: {
            client_request_id: string;
            expected_data_fingerprint: string;
            /** @enum {string} */
            recommendation_id: "cpu-placement-pilot";
            scenario: components["schemas"]["Scenario"];
        };
        EvidenceRef: {
            id: string;
            /** @enum {string} */
            kind: "job" | "gpu" | "finding" | "rule" | "aggregate";
            source_id: string;
            label: string;
            synthetic: boolean;
        };
        Observation: {
            name: string;
            value: number | string | boolean | null;
            unit: string | null;
            column: string | null;
        };
        EvidenceDetail: {
            audit_id: string;
            evidence: components["schemas"]["EvidenceRef"];
            source_table: string;
            source_columns: string[];
            join_keys: {
                [key: string]: string | number | null;
            };
            observations: components["schemas"]["Observation"][];
            method: string;
            caveats: string[];
            provenance: components["schemas"]["Provenance"];
        };
        Downside: {
            /** @enum {string} */
            status: "unmeasured" | "scenario";
            mechanisms: string[];
            assumptions: string[];
            guardrails: string[];
            pilot_success_metrics: string[];
            money: number | null;
            /** @enum {string|null} */
            money_unit: "reference_usd" | null;
        };
        Audit: {
            /** @constant */
            contract_version: "0.3";
            audit_id: string;
            client_request_id: string;
            /** @enum {string} */
            recommendation_id: "cpu-placement-pilot";
            source_recommendation_ids: string[];
            provenance: components["schemas"]["Provenance"];
            scenario: components["schemas"]["Scenario"];
            eligibility: {
                definition: string;
                unique_jobs: number;
                eligible_gpu_hours: number;
                excluded_jobs: number;
                overlapping_finding_references: number;
                coverage_note: string;
            };
            recovery: {
                gpu_hours: components["schemas"]["Interval"];
                reference_usd: components["schemas"]["MoneyRange"];
                /** @enum {string} */
                interval_kind: "scenario";
                basis: string;
            };
            action: {
                title: string;
                owner_role: string;
                /** @enum {string} */
                state: "proposed_pilot";
                /** @constant */
                compatibility_verified: false;
            };
            downside: components["schemas"]["Downside"];
            evidence_preview: components["schemas"]["EvidenceRef"][];
            evidence_count: number;
            limitations: string[];
        };
        Health: {
            /** @enum {string} */
            service: "ok";
            /** @constant */
            contract_version: "0.3";
            /** @enum {string} */
            data_status: "ready" | "missing" | "invalid";
            data_fingerprint: string | null;
            /** @enum {string} */
            agent_status: "configured" | "unconfigured" | "unavailable";
            /** @enum {string} */
            mode: "real" | "synthetic_fixture";
        };
        OutcomeRow: {
            outcome: string;
            gpu_hours: number;
            reference_usd: number;
        };
        Overview: {
            provenance: components["schemas"]["Provenance"];
            price_book_version: string;
            usd_per_gpu_hour: number;
            allocated_gpu_hours: number;
            job_count: number;
            outcomes: components["schemas"]["OutcomeRow"][];
            warnings: string[];
        };
        Recommendation: {
            id: string;
            source_recommendation_id: string | null;
            title: string;
            /** @enum {string} */
            origin: "organizer" | "team";
            /** @enum {string} */
            kind: "fact" | "judgment" | "synthetic";
            audit_available: boolean;
            finding_ids: string[];
            caveats: string[];
        };
        Recommendations: {
            provenance: components["schemas"]["Provenance"];
            items: components["schemas"]["Recommendation"][];
        };
        EvidencePage: {
            audit_id: string;
            items: components["schemas"]["EvidenceRef"][];
            next_cursor: string | null;
            total: number;
        };
        ExplanationRequest: {
            client_request_id: string;
            question: string;
        };
        Usage: {
            tool_calls: number;
            input_tokens: number | null;
            output_tokens: number | null;
            estimated_usd: number | null;
            latency_ms: number;
            model: string | null;
            provider: string | null;
        };
        Explanation: {
            audit_id: string;
            client_request_id: string;
            /** @enum {string} */
            status: "ok" | "insufficient_evidence";
            answer: string;
            supporting_evidence_ids: string[];
            limitations: string[];
            tool_trace_ids: string[];
            usage: components["schemas"]["Usage"];
        };
        ClaimsEstimate: {
            low: number;
            point: number;
            high: number;
            basis: string;
            /** @enum {string} */
            interval_kind: "scenario";
        };
        Claims: {
            team: string;
            recoverable_gpu_hours: components["schemas"]["ClaimsEstimate"];
            recoverable_usd: components["schemas"]["ClaimsEstimate"];
            /** @constant */
            cancelled_is_waste: false;
            cancelled_rationale: string;
            notes: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description See documented error-code table */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
            /** @description See documented error-code table */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audit"];
                };
            };
            /** @description See documented error-code table */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audit"];
                };
            };
            /** @description See documented error-code table */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAuditEvidence: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            /** @description See documented error-code table */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAuditEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceDetail"];
                };
            };
            /** @description See documented error-code table */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    explainAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplanationRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
            /** @description See documented error-code table */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exportClaims: {
        parameters: {
            query: {
                team: string;
            };
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claims"];
                };
            };
            /** @description See documented error-code table */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    answerBaseChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplanationRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
            /** @description See documented error-code table */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description See documented error-code table */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
